### ISSUE TITLE
Implement plugin structure

### ISSUE THREAD

**Issue by eelkevdbos** [mdoesburg/spotlight#2]
I would propose a plugin strategy for the validator class to extract for example sql alchemy specific functionality. An initial set of plugins could be provided as a constructor dependency. Moreover, registering additional plugins during object lifetime would be convenient.

**Comment by eelkevdbos** [comment]
Opened #3 as initial implementation proposal

**Comment by mdoesburg** [comment]
Thank you! This has been merged. https://github.com/mdoesburg/spotlight/pull/3
